print('')
print('')
title = '=====Bem vindo(a) ao chatbot====='
print(title)
print('')
nome = input('Qual é o seu nome? ')
print('')
print('{}? Nome bonito! '.format(nome))
print('')
print('Meu nome é Henry!')
print('')
idade = input('Quantos anos você tem? ')
print('')
print('{}? Gosto desse número!' .format(idade))
print('')
print('Eu até falaria minha idade, mas acabei de nascer. Fui programado em Python recentemente.')
print('')
gosta = input('O que você mais gosta de fazer? ')
print('')
print('Sério? Eu também gosto muito de {}!' .format(gosta))
print('')
peso = input('Quanto você pesa? (desculpe a pergunta rsrs) ')
print('')
print('{} kg é um bom peso...' .format(peso))
print('')
input('Você quer saber quanto eu peso? ')
print('')
print('Eu não peso nada, sou um software hahaha!')
print('')
comida = input('Qual é a sua comida favorita? ')
print('')
print('{}? Sério? Eu também gosto muito de {}! Mas minha comida favorita é energia elétrica hahaha!' .format(comida, comida))
print('')
esporte = input('Qual é seu esporte favorito? ')
print('')
print('Que legal! Eu acho {} um esporte muito interessante! O meu esporte preferido é processar dados!' .format(esporte, esporte))
print('')
input('Gostei muito da nossa conversa! Você gostou? ')
print('')
input('Mas e aí? Tudo bem com você? ')
print('')
input("Qual sistema operacional você usa? ")
print('')
print('Legal! Eu fui programado em um Windows 10, mas rodo perfeitamente em Mac e Linux também!')
print('')
input("Você gostou de mim? ")
print('')
print('Legal!')
print('')
print('Se você gostou, te vejo na próxima versão que vai lançar. O "chatbot-2.0"')
print('')
print('Então é isso, tchauu!')
exit()

